### ISSUE TITLE
Upload File

### ISSUE THREAD

**Issue by artyprog** [nullism/pycnic#15]

**Comment by nullism** [comment]
Hello artyprog,

This is a good candidate for an example. 

Many people choose to base64 encode the file content, and post that data as a json parameter.

Alternatively, if you're posting a file directly, then `self.request.body` will contain the raw body content as read from `wsgi.input`. Accessing `self.request.body` expects a `CONTENT-LENGTH` header was set -- it uses that to read bytes from `wsgi.input`. So, you'd use this property the same way you'd use any `wsgi` file upload. 

Does that answer your question?

**Comment by artyprog** [comment]
This totally answer my question
Thank you Aaron
