### ISSUE TITLE
Its will be better if there any implementation of Middleware concept

### ISSUE THREAD

**Issue by rimantoro** [nullism/pycnic#18]

**Comment by nullism** [comment]
Hi there! Can you elaborate a little bit?

**Comment by disconnect3d** [comment]
Not sure what @rimantoro wanted to say but it would be good to create benchmarks that would use middlewares (if all of the frameworks support such concept) or/and other concepts which are often used by web frameworks as this might return different timings comparing to pure hello world benchmarks.

**Comment by rimantoro** [comment]
Sorry for my empty comment.

I'm trying to implement a middleware like [Laravel Lumen](https://lumen.laravel.com/docs/5.2/middleware) do. After couple days I figure it out and I'm applying in my [project here](https://github.com/rimantoro/my-pycnic-svc) with JWT token auth.

Dont know is the best solution, but its work for me as a middleware.
