### ISSUE TITLE
set_cookie add HttpOnly, Secure flags

### ISSUE THREAD

**Issue by epanov** [nullism/pycnic#22]
Hello. 
How I can add additional params HttpOnly and Secure in self.response.set_cookie? 
Now ";" replaced in set_cookie function and I can't do it.

```python
def set_cookie(self, key, value, expires="", path='/', domain=""):
        value = value.replace(";","") # ; not allowed
        if expires:
            expires = "expires=%s; "%(expires)
        if domain:
            domain = "Domain=%s; "%(domain)
        self.cookie_dict[key] = "%s;%s%s path=%s"%(value, domain, expires, path)
```
May be add two new function args Secure=False, HttpOnly=False?

**Comment by nullism** [comment]
This seems like a good idea to me. What do you think of a more generic use case, such as `flags=`? 

```python
self.response.set_cookie("myCookie", "1234", flags=["HttpOnly", "Secure", "OtherFlag"])
```

I'd change the method to something like:

```python
    def set_cookie(
            self, key, value, expires="", path='/', domain="", flags=[]):
        value = value.replace(";","") # ; not allowed
        if expires:
            expires = "expires=%s; "%(expires)
        if domain:
            domain = "Domain=%s; "%(domain)

        self.cookie_dict[key] = "%s;%s%s path=%s; %s"\
            %(value, domain, expires, path, ";".join(flags))
```

**Comment by epanov** [comment]
Your version with the list of additional params looks better. Great!

**Comment by nullism** [comment]
Cool! I'm just testing it now. I'll create a new PIP build as soon as I finish.  

Example `set_cookie("TestCookie", 12345, path="/test", flags=["HttpOnly", "ExtraFlag"])` returns: 

```Set-Cookie:TestCookie=12345; path=/test; HttpOnly; ExtraFlag```

**Comment by epanov** [comment]
Thank you!

**Comment by nullism** [comment]
This should be in version 0.1.2, now available on Pip. Thanks for helping make Pycnic better!
