### ISSUE TITLE
Support for uwsgi

### ISSUE THREAD

**Issue by Moataz-E** [nullism/pycnic#23]
Hi,

So I have the very basic example on your website setup with the simple get method and the root route. Running it with gunicorn using the following command works perfectly:

> gunicorn quote:app -b :9005

But using uwsgi, I get an invalid request block size so I expand increase the max block size and run the following:

> uwsgi --socket 127.0.0.1:9005 --module quote:app -b 32768

uwsgi seems to run fine but I keep getting empty responses. With gunicorn I was able to retrieve the data correctly from the same request.

Any ideas?

**Comment by nullism** [comment]
Hi Moataz-E, I'll dig into this today. 

Do you have an example request payload and an example of how you're retrieving that?

**Comment by Moataz-E** [comment]
I am using the very simple example on the main website [here](http://pycnic.nullism.com/docs/index.html).

And unfortunately never tried wsgiref.

**Comment by nullism** [comment]
This is working as expected for me. 

I think you want to use `--http` instead of `--socket` with `uwsgi`. 

For example:

`uwsgi --http 0.0.0.0:8080 --module hello:app`

Works perfectly for me, but:

`uwsgi --socket 0.0.0.0:8080 --module hello:app`

Does not.

**Comment by nullism** [comment]
I'm going to close this out. Please let me know if this doesn't work for you.

**Comment by Moataz-E** [comment]
hi nullism,

Unfortunately, I reverted to using gunicorn so can't test uwsgi now.

Feel free to closethis,  I am confident you've replicated the issue and the solution is as you've mentioned.

Thanks!
