### ISSUE TITLE
Not able to return python dictionary variables

### ISSUE THREAD

**Issue by UnKnowN1121** [nullism/pycnic#26]
I'm new to python so not sure if i'm missing something. In the below code when i print the result variable i get the proper output but when i try to return the result i just get this "error": "An unhandled exception occurred during response". i know i should use get but using post since i need to send data which il do later on.. 

```
def post(self):
        url = self.request.environ['PATH_INFO']
        urlarray = url.split('/')
        if urlarray[3]:
            result = db.colletion.find_one({"_id": ObjectId("%s"%(urlarrary[3]))})
        print(result)
        return result
```

**Comment by nullism** [comment]
Hi there!

Do you have debugging on? For example:
```python
class app(WSGI):
    ...
    debug = True
```

If so, and it's still not giving you error information, then I would wrap your code in a `try ... except` block, like so:

```python
def post(self):
    try:
        url = self.request.environ['PATH_INFO']
        urlarray = url.split('/')
        if len(urlarray) > 3: # Do this instead, otherwise it will raise an index error
            result = db.colletion.find_one({"_id": ObjectId("%s"%(urlarrary[3]))})
            return result
        return {"error": "urlarray does not have 3 parts"}    
    except Exception as err:
        raise HTTP_500("Unknown error: %s"%(err))
```
Then simply look at the response (in Developer Tools or whatever is appropriate for your browser). 

Note that I changed a few other things relating to how Python works. When accessing an array (called `list` in Python) with fewer items than the index, Python will throw an exception.

Hope that helps!

**Comment by nullism** [comment]
I'm going to close this out for now.

**Comment by UnKnowN1121** [comment]
Ah Thank you @nullism, i turned on debugging and then found out that the ObjectId of MongoDB wasn't getting converted to json. 



        "TypeError: ObjectId('5a219074e018e00b21f3eb05') is not JSON serializable",

i added this before the return result statement `result["_id"] = str(result["_id"])`, which solved it. thanks for pointing out the index error too.
:)
