### ISSUE TITLE
How to get GET variables (query string)?

### ISSUE THREAD

**Issue by OwenChia** [nullism/pycnic#5]
Using environ like this ?
```python
query_string = self.request.environ["QUERY_STRING"]
variables = dict(urllib.parse.parse_qsl(query_string))
```

Is there a better way to do this?

**Comment by nullism** [comment]
Hello OwenChia,

Pycnic is a RESTful/JSON API server, and query strings don't really fit with that, as parameters are passed to the method itself, e.g `/myapi/([a-z]+)/([0-9]+)` might map to a method like `get(self, object, object_id)`. 

Do you have an example of how you'd use this? 

Thanks!

**Comment by OwenChia** [comment]
Thanks for your reply.
> Pycnic is a RESTful/JSON API server, and query strings don't really fit with that
`...`

That makes sense, using query strings for RESTful API is not a good idea.

BTW, you made a very cool project.

**Comment by nullism** [comment]
Aha! After doing some research, apparently it is considered acceptable to use "filters" as part of the query string -- an example would be with Google Maps API. So I'm going to keep this open if that's okay with you. I'm working on a Python 2 & 3 backwards compatible way of handing this.
