### ISSUE TITLE
"Docs" Submenu not visible on Website

### ISSUE THREAD

**Issue by felixbuenemann** [nullism/pycnic#7]
THere's a problem with the top menu on the pycnic docs website.

The class `.top-menu` has `overflow: hidden` set, which hides the dropdown from the "Docs" submenu. Removing `overflow: hidden` from that class fixes the issue.

Tested in latest Safari and Chrome on Mac OS X.

**Comment by nullism** [comment]
Hey there,

Thanks for letting me know!

I was unable to reproduce on Chrome Linux, Chrome Windows, Firefox Linux, Firefox Windows, or IE. 

I changed that setting anyway, as it doesn't seem to affect anything with those browsers. 

Did that fix the issue for you?

**Comment by felixbuenemann** [comment]
Yes, thanks!
