### ISSUE TITLE
Response headers persisted between requests

### ISSUE THREAD

**Issue by felixbuenemann** [nullism/pycnic#8]
The response headers are shared between requests.

If I do `self.response.set_header('x-foo', 'bar')` on request one, and don't set it in request two, the header is still present in the response to request two.

**Comment by nullism** [comment]
Oh wow. Yeah, I changed the way it handled the Response object's "header_dict" property. Good find. I'm testing my fix now. Thanks!

**Comment by nullism** [comment]
I can no longer reproduce with this current fix. Please feel free to reopen this if you still experience it after adding the fix. I'm adding a new PyPI build now (0.0.7), so you'll be able to `pip install pycnic --upgrade` in a couple of minutes. Thanks again for finding this &mdash; I appreciate it very much.

**Comment by felixbuenemann** [comment]
Thanks, working fine now!
